import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.tsx/page";
import Footer from "./components/Footer.tsx/page";
import Cardmain from "./components/Cardmain.tsx/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
         <Navbar /> 
        {children}
        <Cardmain /> 
         <Footer />  
        </body>
            </html>
  );
}
